// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFfPowjcOV6x_Ro5JvPnTf83t9sIYL2t0',
    appId: '1:639910362193:web:981e114a85dbeaec998c70',
    messagingSenderId: '639910362193',
    projectId: 'eos-hackover3',
    authDomain: 'eos-hackover3.firebaseapp.com',
    storageBucket: 'eos-hackover3.appspot.com',
    measurementId: 'G-8GD9P1PL62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCompa2ezQ_kwB5dgnn-QgQsDvkoXfL1H0',
    appId: '1:639910362193:android:b6a8c13f11b5ac10998c70',
    messagingSenderId: '639910362193',
    projectId: 'eos-hackover3',
    storageBucket: 'eos-hackover3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrf0bWWyJXz3rGENtZuRFkezxortv1rZo',
    appId: '1:639910362193:ios:66c4f42a900ca4e8998c70',
    messagingSenderId: '639910362193',
    projectId: 'eos-hackover3',
    storageBucket: 'eos-hackover3.appspot.com',
    iosClientId: '639910362193-8f1g5jr665aj3qj8dp7tj7gegv0rtlf9.apps.googleusercontent.com',
    iosBundleId: 'com.prerak.eosHackover3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrf0bWWyJXz3rGENtZuRFkezxortv1rZo',
    appId: '1:639910362193:ios:66c4f42a900ca4e8998c70',
    messagingSenderId: '639910362193',
    projectId: 'eos-hackover3',
    storageBucket: 'eos-hackover3.appspot.com',
    iosClientId: '639910362193-8f1g5jr665aj3qj8dp7tj7gegv0rtlf9.apps.googleusercontent.com',
    iosBundleId: 'com.prerak.eosHackover3',
  );
}
