# Generated by Django 3.1 on 2022-10-05 00:17

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_events_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_background', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('organiztion_paper', models.ImageField(blank=True, null=True, upload_to='')),
                ('organization_website', models.CharField(blank=True, max_length=255)),
                ('organization_knownfor', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
