# Generated by Django 3.1 on 2022-10-05 00:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221005_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='organiztion_paper',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
