# Generated by Django 3.1 on 2022-10-05 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221005_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_enrolled', to='accounts.events')),
                ('event_enrolled_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_enrolled_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
